admin/controllers/RedirectController.php
<?php

namespace admin\controllers;

use admin\models\setting\RedirectSearch;
use common\models\site\Redirect;
use Throwable;
use Yii;
use yii\db\StaleObjectException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class RedirectController extends SecurityController
{
    public function actionIndex()
    {
        $searchModel = new RedirectSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        $this->view->title = 'Список';
        $this->view->params['breadcrumbs'][] = [
            'label' => $this->view->title,
        ];

        return $this->render(
            'index',
            [
                'dataProvider' => $dataProvider,
                'searchModel' => $searchModel,
            ]
        );
    }

    public function actionCreate()
    {
        $model = new Redirect();

        $post = Yii::$app->request->post();
        if ($post) {
            if ($model->load($post)) {
                $isValid = $model->validate() ;
                if ($isValid) {
                    $model->save();
                    Yii::$app->session->addFlash('success', 'Успешно создано');

                    return $this->redirect(
                        [
                            'update',
                            'id' => $model->id,
                        ]
                    );
                }
            }

            foreach ($model->getErrorSummary(true) as $error) {
                Yii::$app->session->addFlash('error', $error);
            }
        }

        $this->view->title = 'Создание';
        $this->view->params['breadcrumbs'][] = [
            'label' => 'Список',
            'url' => ['index'],
        ];
        $this->view->params['breadcrumbs'][] = $this->view->title;

        //        $model->active = 1;

        return $this->render(
            '_form',
            [
                'model' => $model,
            ]
        );
    }

    public function actionUpdate($id)
    {
        /* @var Redirect $model */
        $model = Redirect::findOne(['id' => $id]);
        if ($model === null) {
            throw new NotFoundHttpException;
        }

        $post = Yii::$app->request->post();
        if ($post) {
            if ($model->load($post)) {
                $isValid = $model->validate();
                if ($isValid) {
                    $model->save();
                    Yii::$app->session->addFlash('success', 'Успешно обновлено');

                    return $this->redirect(
                        [
                            'update',
                            'id' => $model->id,
                        ]
                    );
                }
            }

            foreach ($model->getErrorSummary(true) as $error) {
                Yii::$app->session->addFlash('error', $error);
            }
        }

        $this->view->title = "Изменение {$model->id}";
        $this->view->params['breadcrumbs'][] = [
            'label' => 'Список',
            'url' => ['index'],
        ];
        $this->view->params['breadcrumbs'][] = $model->id;

        return $this->render(
            '_form',
            [
                'model' => $model,
            ]
        );
    }

    /**
     * @param $id
     *
     * @return Response
     * @throws NotFoundHttpException
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        /* @var Redirect $model */
        $model = Redirect::findOne(['id' => $id]);
        if ($model === null) {
            throw new NotFoundHttpException;
        }

        if ($model->delete()) {
            Yii::$app->session->addFlash('success', 'Успешно удалено');
        } else {
            Yii::$app->session->addFlash('error', 'Ошибка удаления');
        }

        return $this->redirect('index');
    }
}

admin/controllers/SettingController.php
<?php

namespace admin\controllers;

use admin\models\setting\SettingSearch;
use common\models\site\Setting;
use Throwable;
use Yii;
use yii\db\StaleObjectException;
use yii\web\NotFoundHttpException;
use yii\web\Response;

class SettingController extends SecurityController
{
    public function actionIndex()
    {
        $searchModel = new SettingSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->get());

        $this->view->title = 'Список';
        $this->view->params['breadcrumbs'][] = [
            'label' => $this->view->title
        ];

        return $this->render('index', [
            'dataProvider' => $dataProvider,
            'searchModel' => $searchModel
        ]);
    }

    public function actionCreate()
    {
        $model = new Setting();

        $post = Yii::$app->request->post();
        if ($post) {
            if ($model->load($post) && $model->save()) {
                Yii::$app->session->addFlash('success', 'Успешно создано');

                return $this->redirect([
                    'update',
                    'id' => $model->id
                ]);
            }

            foreach ($model->getErrors() as $error) {
                Yii::$app->session->addFlash('error', $error);
            }
        }

        $this->view->title = 'Создание';
        $this->view->params['breadcrumbs'][] = [
            'label' => 'Список',
            'url' => ['index']
        ];
        $this->view->params['breadcrumbs'][] = $this->view->title;

        return $this->render('_form', [
            'model' => $model
        ]);
    }

    public function actionUpdate($id)
    {
        /* @var Setting $model */
        $model = Setting::findOne(['id' => $id]);
        if ($model === NULL) {
            throw new NotFoundHttpException;
        }

        $post = Yii::$app->request->post();
        if ($post) {
            if ($model->load($post) && $model->save()) {
                Yii::$app->session->addFlash('success', 'Успешно обновлено');

                return $this->redirect([
                    'update',
                    'id' => $model->id
                ]);
            }

            foreach ($model->getErrors() as $error) {
                Yii::$app->session->addFlash('error', $error);
            }
        }

        $this->view->title = 'Изменение "' . $model->code . '"';
        $this->view->params['breadcrumbs'][] = [
            'label' => 'Список',
            'url' => ['index']
        ];
        $this->view->params['breadcrumbs'][] = $model->code;

        return $this->render('_form', [
            'model' => $model
        ]);
    }

    /**
     * @param $id
     * @return Response
     * @throws NotFoundHttpException
     * @throws Throwable
     * @throws StaleObjectException
     */
    public function actionDelete($id)
    {
        /* @var Setting $model */
        $model = Setting::findOne(['id' => $id]);
        if ($model === NULL) {
            throw new NotFoundHttpException;
        }

        if ($model->delete()) {
            Yii::$app->session->addFlash('success', 'Успешно удалено');
        } else {
            Yii::$app->session->addFlash('error', 'Ошибка удаления');
        }

        return $this->redirect('index');
    }
}

admin/views/layouts/auth.php
<?php
use backend\assets\AppAsset;
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

dmstr\web\AdminLteAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="login-page">

<?php $this->beginBody() ?>

    <?= $content ?>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

admin/views/layouts/content.php
<?php

use Carbon\Carbon;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\widgets\Breadcrumbs;
use dmstr\widgets\Alert;

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo Html::encode($this->title);
                } else {
                    echo Inflector::camel2words(
                        Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?= Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ); ?>
    </section>

    <section class="content">
        <?= Alert::widget() ?>
        <?= $content ?>
    </section>
</div>

<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <b>Версия</b> 1.0
    </div>
    <strong>Copyright &copy; 2020-<?= Carbon::now()->year; ?> <a href="http://paterm.tk" target="_blank">Paterm Studio</a>.</strong> All rights
    reserved.
</footer>


<div class='control-sidebar-bg'></div>

admin/views/layouts/header.php
<?php
use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */
/* @var \common\models\access\User $user */
$user = Yii::$app->user->identity;
$userIcon = $user->photo ? $user->photo->getUrl() : $directoryAsset . '/img/user2-160x160.jpg';
?>

<header class="main-header">

    <?= Html::a('<span class="logo-mini">Golos</span><span class="logo-lg">' . Yii::$app->name . '</span>', Yii::$app->homeUrl, ['class' => 'logo']) ?>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $userIcon; ?>" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?= $user->firstname; ?> <?= $user->lastname; ?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="<?= $userIcon ?>"
                                 class="img-circle"
                                 alt="User Image"
                            />
                            <p>
                                <?= $user->firstname; ?> <?= $user->lastname; ?> - <?= $user->getTypeName(); ?>
                                <small><?= $user->city ? $user->city->title : '' ?></small>
                            </p>
                        </li>
                        <!-- Menu Body -->

                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-right">
                                <?= Html::a(
                                    'Выйти',
                                    ['/default/logout'],
                                    ['data-method' => 'post', 'class' => 'btn btn-default btn-flat']
                                ) ?>
                            </div>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

admin/views/layouts/left.php
<?php
/** @var \common\models\access\User $user */
$user = Yii::$app->user->identity;
$userIcon = $user->photo ? $user->photo->getUrl() : $directoryAsset . '/img/user2-160x160.jpg';;
?>
<aside class="main-sidebar">

    <section class="sidebar">

        <!-- Sidebar user panel -->
        <div class="user-panel">
            <div class="pull-left image">
                <img src="<?= $userIcon; ?>" class="img-circle" alt="User Image"/>
            </div>
            <div class="pull-left info">
                <p><?= $user->firstname; ?> <?= $user->lastname; ?></p>
            </div>
        </div>

        <!-- search form -->
        <!--        <form action="#" method="get" class="sidebar-form">-->
        <!--            <div class="input-group">-->
        <!--                <input type="text" name="q" class="form-control" placeholder="Search..."/>-->
        <!--              <span class="input-group-btn">-->
        <!--                <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>-->
        <!--                </button>-->
        <!--              </span>-->
        <!--            </div>-->
        <!--        </form>-->
        <!-- /.search form -->

        <?= dmstr\widgets\Menu::widget(
            [
                'options' => ['class' => 'sidebar-menu tree', 'data-widget' => 'tree'],
                'items' => [
                    ['label' => 'Меню управления', 'options' => ['class' => 'header']],
                    [
                        'label' => 'Пользователи',
                        'icon' => 'users',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Клиенты', 'icon' => 'users', 'url' => ['/user-client']],
                            ['label' => 'Голоса', 'icon' => 'users', 'url' => ['/user-announcer']],
                            ['label' => 'Чаты', 'icon' => 'users', 'url' => ['/chat']],
                            ['label' => 'Счета', 'icon' => 'users', 'url' => ['/bill']],
                            ['label' => 'Вывод средств', 'icon' => 'users', 'url' => ['/pay']],
                            ['label' => 'Долг по комиссии', 'icon' => 'users', 'url' => ['/commission']],
                        ],
                    ],

                    [
                        'label' => 'Контент пользователей',
                        'icon' => 'share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Отзывы о пользователе', 'icon' => 'newspaper-o', 'url' => ['/review']],
                            ['label' => 'Отзывы о Голосмаркет', 'icon' => 'newspaper-o', 'url' => ['/review-service']],
                            ['label' => 'Обратная связь', 'icon' => 'newspaper-o', 'url' => ['/feedback']],
                        ]
                    ],

                    [
                        'label' => 'Контент сервиса',
                        'icon' => 'share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Новости', 'icon' => 'newspaper-o', 'url' => ['/content-news']],
                            ['label' => 'FAQ', 'icon' => 'newspaper-o', 'url' => ['/content-faq']],
                            ['label' => 'Текст на страницах', 'icon' => 'newspaper-o', 'url' => ['/content-helper']],
                            ['label' => 'Меню', 'icon' => 'newspaper-o', 'url' => ['/content-menu']],
                            ['label' => 'Страницы', 'icon' => 'newspaper-o', 'url' => ['/content-page']],
//                            ['label' => 'Вопросы', 'icon' => 'newspaper-o', 'url' => ['/content-question']],
//                            ['label' => 'Ответы', 'icon' => 'newspaper-o', 'url' => ['/content-answer']],
                            ['label' => 'Главное изображение', 'icon' => 'newspaper-o', 'url' => ['/content-banner']],
                            ['label' => 'Подборки', 'icon' => 'newspaper-o', 'url' => ['/content-collection']],
                            ['label' => 'Письмо для оплаты комиссии', 'icon' => 'newspaper-o', 'url' => ['/content-commission-mail']],
                        ]
                    ],

                    [
                        'label' => 'Фильтры дикторов',
                        'icon' => 'share',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Тембр', 'icon' => 'users', 'url' => ['/user-timber']],
                            ['label' => 'Таги', 'icon' => 'users', 'url' => ['/user-tag']],
                            ['label' => 'Презентации', 'icon' => 'users', 'url' => ['/user-presentation']],
                            ['label' => 'Языки', 'icon' => 'users', 'url' => ['/user-language']],
                            ['label' => 'Пол', 'icon' => 'users', 'url' => ['/user-gender']],
                            ['label' => 'Возраст', 'icon' => 'users', 'url' => ['/user-age']],
                        ],
                    ],

                    ['label' => 'План', 'icon' => 'cog', 'url' => ['admin-plan/index']],
                    [
                        'label' => 'Настройки',
                        'icon' => 'cog',
                        'url' => '#',
                        'items' => [
                            ['label' => 'Настройки', 'icon' => 'cog', 'url' => ['setting/index']],
                            ['label' => 'Редирект', 'icon' => 'cog', 'url' => ['redirect/index']],
                            ['label' => 'Robots.txt', 'icon' => 'cog', 'url' => ['seo/robots']],
                        ],
                    ],




                    ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug']],
//                    ['label' => 'Login', 'url' => ['site/login'], 'visible' => Yii::$app->user->isGuest],
//                    [
//                        'label' => 'Some tools',
//                        'icon' => 'share',
//                        'url' => '#',
//                        'items' => [
//                            ['label' => 'Gii', 'icon' => 'file-code-o', 'url' => ['/gii'],],
//                            ['label' => 'Debug', 'icon' => 'dashboard', 'url' => ['/debug'],],
//                            [
//                                'label' => 'Level One',
//                                'icon' => 'circle-o',
//                                'url' => '#',
//                                'items' => [
//                                    ['label' => 'Level Two', 'icon' => 'circle-o', 'url' => '#',],
//                                    [
//                                        'label' => 'Level Two',
//                                        'icon' => 'circle-o',
//                                        'url' => '#',
//                                        'items' => [
//                                            ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
//                                            ['label' => 'Level Three', 'icon' => 'circle-o', 'url' => '#',],
//                                        ],
//                                    ],
//                                ],
//                            ],
//                        ],
//                    ],
                ],
            ]
        ) ?>

    </section>

</aside>

admin/views/layouts/main.php
<?php

use yii\helpers\Html;

/* @var $this \yii\web\View */
/* @var $content string */

admin\assets\AppAsset::register($this);


dmstr\web\AdminLteAsset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="https://unpkg.com/ionicons@4.5.10-0/dist/css/ionicons.min.css" rel="stylesheet">
    <?php $this->head() ?>
</head>
<body class="hold-transition skin-blue sidebar-mini">
<?php $this->beginBody() ?>
<div class="wrapper">

    <?= $this->render(
        'header.php',
        ['directoryAsset' => $directoryAsset]
    ); ?>

    <?= $this->render(
        'left.php',
        ['directoryAsset' => $directoryAsset]
    ); ?>

    <?= $this->render(
        'content.php',
        ['content' => $content, 'directoryAsset' => $directoryAsset]
    ); ?>

</div>

<?php $this->endBody(); ?>
</body>
</html>
<?php $this->endPage(); ?>